--liquibase formatted sql

--changeset sromanov:1
DROP TABLE IF EXISTS limit_ CASCADE;

--changeset sromanov:2
DROP TABLE IF EXISTS card_ CASCADE;

--changeset sromanov:3
CREATE TABLE IF NOT EXISTS card_ (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    balance NUMERIC(19, 4) NOT NULL CHECK (balance >= 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'FROZEN', 'BLOCKED'))
);

--changeset sromanov:4
CREATE TABLE IF NOT EXISTS card_details (
    id BIGSERIAL PRIMARY KEY,
    card_id BIGINT NOT NULL UNIQUE REFERENCES card_(id) ON DELETE CASCADE,
    number VARCHAR NOT NULL UNIQUE,
    expiration_date VARCHAR(5) NOT NULL,
    cvv CHAR(3) NOT NULL
);

--changeset sromanov:5
CREATE TABLE IF NOT EXISTS card_metadata (
    id BIGSERIAL PRIMARY KEY,
    card_id BIGINT NOT NULL UNIQUE REFERENCES card_(id) ON DELETE CASCADE,
    issuer VARCHAR NOT NULL,
    payment_scheme VARCHAR NOT NULL
);

--changeset sromanov:6
CREATE TABLE IF NOT EXISTS limit_ (
    id BIGINT UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_id BIGINT NOT NULL REFERENCES card_(id) ON DELETE CASCADE,
    limit_amount NUMERIC(19, 4) NOT NULL CHECK (limit_amount >= 0),
    set_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    removed_at TIMESTAMP WITHOUT TIME ZONE
);
