{
 "title": "Get Card",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "stat",
   "description": "Показывает процент успешных запросов (не 5xx ошибок)",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\".*actuator.*|.*prometheus.*\", status!~\"5..\"}[5m]))\r\n/\r\nsum(rate(http_server_requests_seconds_count{uri!~\".*actuator.*|.*prometheus.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "description": "Сколько запросов в секунду прямо сейчас",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\".*actuator.*|.*prometheus.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Critical Alerts",
   "type": "alertlist",
   "description": "Показывает список сработавших алертов",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 }
  },
  {
   "title": "Requests Rate by Endpoint (Top 5)",
   "type": "timeseries",
   "description": "Показывает, какие ручки вызывают чаще всего",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, sum by (uri) (rate(http_server_requests_seconds_count{uri!~\".*actuator.*|.*prometheus.*\"}[1m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate by Code",
   "type": "timeseries",
   "description": "Разбивка ответов: 200 (ОК), 400 (Client Error), 500 (Server Error)",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{uri!~\".*actuator.*|.*prometheus.*\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "timeseries",
   "description": "Линия, показывающая, сколько ждет \"самый неудачливый\" пользователь",
   "gridPos": { "h": 11, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_requests_seconds_bucket{uri!~\".*actuator.*|.*prometheus.*\"}[5m])))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "description": "График для поиска тормозов",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_server_requests_seconds_bucket{uri!~\".*actuator.*|.*prometheus.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads count",
   "type": "timeseries",
   "description": "Количество потоков в использовании",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "threads" }
   ]
  },
  {
   "title": "Heap Memory & GC Pauses",
   "type": "timeseries",
   "description": "Сколько памяти занято и как сильно тормозит сборщик мусора",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "Heap"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum[1m]))",
     "legendFormat": "GC Time"
    }
   ]
  }
 ]
}