{
 "title": "services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, application)"
    }
   },
   {
    "name": "uri",
    "label": "Endpoint",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=~\"$service\", uri!~\".*actuator.*|.*prometheus.*|.*/api/v1/cards/\\\\*\\\\*\"}, uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top-5 endpoints latency",
   "type": "status-history",
   "description": "Задержка топ-5 загруженных эндпоинтов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "# 1. Основной расчет\r\nhistogram_quantile(0.99, \r\n  sum by (le, uri) (rate(http_server_requests_seconds_bucket{application=~\"$service\", uri=~\"$uri\", uri!~\".*actuator.*|.*prometheus.*|.*/api/v1/cards/\\\\*\\\\*\"}[$__rate_interval]))\r\n)\r\n\r\n# 2. Фильтр\r\nand on(uri) (\r\n  topk(5, \r\n    avg_over_time(\r\n      histogram_quantile(0.99, \r\n        sum by (le, uri) (rate(http_server_requests_seconds_bucket{application=~\"$service\", uri=~\"$uri\", uri!~\".*actuator.*|.*prometheus.*|.*/api/v1/cards/\\\\*\\\\*\"}[$__rate_interval]))\r\n      )[$__range:]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General status codes",
   "type": "timeseries",
   "description": "Общие статус коды сервиса",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{application=~\"$service\", uri=~\"$uri\", uri!~\".*actuator.*|.*prometheus.*|.*/api/v1/cards/\\\\*\\\\*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 endpoints RPS",
   "type": "timeseries",
   "description": "RPS топ-5 эндпоинтов по использованию",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, sum by (uri) (rate(http_server_requests_seconds_count{application=~\"$service\", uri=~\"$uri\", uri!~\".*actuator.*|.*prometheus.*|.*/api/v1/cards/\\\\*\\\\*\"}[1m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "General RPS",
   "type": "timeseries",
   "description": "Общий счетчик запросов в секунду",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$service\", uri=~\"$uri\", uri!~\".*actuator.*|.*prometheus.*|.*/api/v1/cards/\\\\*\\\\*\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  }
 ]
}