--liquibase formatted sql

--changeset sromanov:1
CREATE TABLE IF NOT EXISTS refresh_token
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    token VARCHAR NOT NULL UNIQUE
);

--changeset sromanov:2
CREATE TABLE IF NOT EXISTS user_roles
(
    user_id UUID,
    role VARCHAR
);